apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloappnew
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloappnew
  template:
    metadata:
      labels:
        app: helloappnew
    spec:
      containers:
      - name: dind
        image: docker:26.0.1-dind
        resources:
            requests:
                cpu: 10m
                memory: 300Mi
            limits:
                cpu: 2
                memory: 300Mi
        securityContext:
            privileged: true
            allowPrivilegeEscalation: true
        command: ["dockerd", "--host=unix:///var/run/docker.sock", "--host=tcp://0.0.0.0:2375", "--tls=false"]
        volumeMounts:
          - name: docker-graph-storage
            mountPath: /var/lib/docker
      - name: helloappnew
        image: chanikya1409/chanikya:latest
        # imagePullPolicy: Always
        ports:
          - containerPort: 4444
        env:
          - name: DOCKER_HOST
            value: tcp://localhost:2375
      volumes:
      - name: docker-graph-storage
        emptyDir: {}