
    FROM ubuntu:22.04
    RUN apt-get update && apt-get install -y python3 python3-pip

    COPY uploads/demo/requirements.txt /
    RUN pip install --no-cache-dir -r requirements.txt

    COPY uploads/demo/demo.py /
    EXPOSE 4444

    CMD ["bash", "-c","sleep infinity"]
    